### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by AnonymousWebHacker** [simonghpub/peertube-plugin-privacysettings#1]
There is no description of the repo. Does this allow me to block videos for people who are not registered?

**Comment by simonghpub** [comment]
No, not directly at least - it disables the three other "Privacy" settings on the Publish/Upload page, making the "Internal" setting the only available.

**Comment by AnonymousWebHacker** [comment]
It would be ideal if you could disable the videos for the unregistered, only allowing instances like mastodon or others of peertube
