### ISSUE TITLE
Update to support password-protected privacy

### ISSUE THREAD

**Issue by TheCableGuy99** [simonghpub/peertube-plugin-privacysettings#2]
Hi,

Can this be updated to support the password protect privacy option as well please?

I personally want to disable all options apart from "Internal".

Thank you!

**Comment by simonghpub** [comment]
Sure, I added that in the latest update.
Please confirm whether it is working or not, I currently dont have a active PeerTube installation to test it.

**Comment by TheCableGuy99** [comment]
Hey, thank you for this. I'm new to this software and it's not showing an update so I presume I had to uninstall it and re-install it.

I've tried that but it's failing to install each time. It just says:
Error
Cannot install plugin peertube-plugin-privacysettings

There's nothing in the GUI logs, is there some logs in the CLi I can check somewhere or is there a manual way to install it?

Thanks!

**Comment by simonghpub** [comment]
According to https://docs.joinpeertube.org/contribute/plugins#publishing it would probably first have showed an update after 24hours.  On that page they link to a site where you can view the available indexed plugins, https://packages.joinpeertube.org/api/v1/plugins , to my surprise this plugin is not in the list - it probably isn't compatible with the latest version - will try and look on it at some point.

The logs should be in /var/www/peertube/storage/logs/ as far as I remember.

**Comment by simonghpub** [comment]
> Hey, thank you for this. I'm new to this software and it's not showing an update so I presume I had to uninstall it and re-install it.
> 
> I've tried that but it's failing to install each time. It just says: Error Cannot install plugin peertube-plugin-privacysettings
> 
> There's nothing in the GUI logs, is there some logs in the CLi I can check somewhere or is there a manual way to install it?
> 
> Thanks!

I have had a chance to test it now and the latest version of the plugin (1.0.3) works (tested on PeerTube version 6.0.3) :)
The plugin can now again be found and installed from the plugin list within PeerTube's webinterface:
![Unavngivet](https://github.com/simonghpub/peertube-plugin-privacysettings/assets/5131319/ff907e0e-a9d6-40b0-8bd9-3f79ac7235af)
